apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyroscope
  labels:
    app: pyroscope
spec:
  replicas: 1
  template:
    metadata:
      name: pyroscope
      labels:
        app: pyroscope
    spec:
      containers:
        - name: pyroscope
          image: pyroscope/pyroscope:latest
          args:
            - server
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: pyroscope
